type Query {
	login(username: String!, password: String!): loginResponse
	recPass(email: String!): genericResponse
}

type Mutation {
	registration(
		username: String!
		email: String!
		password: String!
		password_confirm: String!
	): genericResponse
}

type genericResponse {
	response: String!
	responseStatus: String!
}

type loginResponse {
	response: String!
	token: String!
	responseStatus: String!
}
