type Query {
	login(username: String!, password: String!): loginResponse
	recPass(email: String!): genericResponse
	charactersList(token: String!): [characterData]
	setCharacter(token: String!, characterId: Int!): loginResponse
}

type Mutation {
	registration(
		username: String!
		email: String!
		password: String!
		password_confirm: String!
	): genericResponse
}

type genericResponse {
	response: String!
	responseStatus: String!
}

type loginResponse {
	response: String!
	token: String
	responseStatus: String!
}

type characterData {
	id: ID
	name: String
	surname: String
	age: Int
	miniavatar: String
	profilePic: String
	nickname: String
}
